/* @flow */

module.exports = {
    CHANGE_EVENT: 'relax:change',
    VIEW_ACTION: 'VIEW_ACTION',
    SERVER_ACTION: 'SERVER_ACTION',
    PLATFORM_ACTION: 'PLATFORM_ACTION',
    SERVICE_ACTION: 'SERVICE_ACTION'
};
